# Generated by Django 5.1.5 on 2025-02-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottopic',
            name='impact_1',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hottopic',
            name='impact_2',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hottopic',
            name='impact_3',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
