# Generated by Django 5.1.5 on 2025-02-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0003_hottopic_impact_1_hottopic_impact_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottopic',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
