# Generated by Django 5.1.5 on 2025-02-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0004_hottopic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottopic',
            name='group_id',
            field=models.IntegerField(default=0, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
