# Generated by Django 5.1.5 on 2025-02-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklisting',
            options={'verbose_name_plural': 'StockListings'},
        ),
        migrations.RenameField(
            model_name='stocklisting',
            old_name='market_cap',
            new_name='code',
        ),
        migrations.AddField(
            model_name='stocklisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklisting',
            name='group_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklisting',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stocklisting',
            name='number_of_shares',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklisting',
            name='total_shares_value',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
