# Generated by Django 5.1.5 on 2025-02-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_stocklisting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklisting',
            name='date',
            field=models.CharField(),
        ),
    ]
