# Generated by Django 5.1.5 on 2025-02-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_stocklisting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insidertransaction',
            old_name='transaction',
            new_name='transaction_price_text',
        ),
        migrations.RenameField(
            model_name='insidertransaction',
            old_name='type',
            new_name='transaction_type',
        ),
        migrations.RenameField(
            model_name='insidertransaction',
            old_name='value',
            new_name='transaction_value_text',
        ),
        migrations.AddField(
            model_name='insidertransaction',
            name='number_of_shares',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insidertransaction',
            name='transaction_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insidertransaction',
            name='transaction_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='company',
            table='',
        ),
    ]
