# Generated by Django 5.1.5 on 2025-02-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_transaction_insidertransaction_transaction_price_text_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
    ]
