# Generated by Django 5.1.5 on 2025-02-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_hottopic_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hottopic',
            name='group_id',
            field=models.IntegerField(editable=False),
        ),
    ]
