# Generated by Django 5.1.5 on 2025-02-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_company_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
