# Generated by Django 5.1.5 on 2025-02-19 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_company_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='annual_dividend',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='average_fair_value',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='cod',
            new_name='fiscal_date_ending',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='discounted_cash_flow_fair_value',
            new_name='week_52_high_low',
        ),
        migrations.RemoveField(
            model_name='company',
            name='earnings_per_share',
        ),
        migrations.RemoveField(
            model_name='company',
            name='economic_value_added_fair_value',
        ),
        migrations.RemoveField(
            model_name='company',
            name='market',
        ),
        migrations.RemoveField(
            model_name='company',
            name='return_on_equity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='company',
            name='shareholders_yield',
        ),
        migrations.AddField(
            model_name='company',
            name='analyst_target_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='current_asset_to_liability_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='day_200_moving_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='day_50_moving_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='ebitda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='ev_to_ebitda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='market_capitalization',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='operating_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='price_to_earnings_fair_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='price_to_sales_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='quarterly_earnings_growth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='quarterly_revenue_growth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='shareholder_equity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='total_assets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='total_liabilities',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insidertransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insidertransaction',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='altman_z_score',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='debt_to_equity_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='net_income',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='peter_lynch_fair_value',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
