# Generated by Django 5.1.5 on 2025-02-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_company_altman_z_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='week_52_high_low',
        ),
        migrations.AddField(
            model_name='company',
            name='week_52_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='week_52_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
