# Generated by Django 5.1.5 on 2025-02-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_remove_company_week_52_high_low_company_week_52_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
