# Generated by Django 5.1.5 on 2025-02-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
