# Generated by Django 5.1.5 on 2025-05-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottopic',
            name='article_url',
            field=models.URLField(default='1'),
            preserve_default=False,
        ),
    ]
